project_name: mc-server-runner
release:
  github:
    owner: itzg
    name: mc-server-runner
brews:
  - install: |
      bin.install "mc-server-runner"
builds:
- goos:
  - linux
  - windows
  goarch:
  - amd64
  - arm
  - arm64
  goarm:
  - "6"
  - "7"
  ignore:
    - goos: windows
      goarch: arm
    - goos: windows
      goarch: arm64
  main: .
  env:
    - CGO_ENABLED=0
  binary: mc-server-runner
archives:
  - format_overrides:
      - goos: windows
        format: zip
changelog:
  filters:
    exclude:
      - '^ci:'
      - '^misc:'
      - '^docs:'